import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className="w-full bg-whiteTheme overflow-hidden">
        <main>
          <div
            className="grid grid-cols-[250px_1fr] gap-5 p-4 min-h-screen
      "
          >
            <section className="bg-contentTheme rounded-2xl shadow-2xl p-4">
              section 1
            </section>
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
